#! /bin/python

import sys;
import os;
import requests;
import subprocess;
import urllib.parse;
import tempfile;

def mime_install():
	desktop = """[Desktop Entry]
Name=zsrload
Comment=ZSR Volume Loader
Exec=zsrload %U
Terminal=false
Type=Application
MimeType=application/x-zsr
""";
	mimespec = """<?xml version="1.0"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
<mime-type type="application/x-zsr">
<comment>ZSR content archive</comment>
<glob-deleteall/>
<glob pattern="*.zsr"/>
</mime-type>
</mime-info>
""";
	local = os.environ["HOME"] + "/.local/share/";
	dtfile = local + "applications/zsrload.desktop";
	msfile = local + "mime/packages/application-x-zsr.xml";
	dtout = open(dtfile, "w");
	dtout.write(desktop);
	dtout.close();
	msout = open(msfile, "w");
	msout.write(mimespec);
	msout.close();
	# subprocess.call(["xdg-mime", "install", msout.name]);
	subprocess.call(["update-desktop-database", local + "applications"]);
	subprocess.call(["update-mime-database", local + "mime"]);

def usage_exit():
	print("Usage: zsrload --install\n       zsrload [-h <host>] <path>");
	exit(1);

host = "localhost:2234";
install = False;
path = None;

argind = 1;
while argind < len(sys.argv):
	if sys.argv[argind] == "-h" or sys.argv[argind] == "--host":
		if argind >= len(sys.argv) - 1: usage_exit();
		host = sys.argv[argind + 1];
		argind += 1;
	elif sys.argv[argind] == "--install":
		if len(sys.argv) != 2: usage_exit();
		install = True;
	elif path is not None: usage_exit();
	else: path = sys.argv[argind];
	argind += 1;

if install:
	mime_install();
	exit(0);

if path is None: usage_exit();
loadurl = "http://{host}/external/%s".format(host=host);
viewurl = "http://{host}/view/%s".format(host=host);

# print(loadurl % (urllib.parse.quote(path, safe="")));
res = requests.get(loadurl % (urllib.parse.quote(path, safe="")));
if res.status_code != 200:
	print("Could not open file: %d" % (res.status_code));
	exit(2);
volid = res.text;
if "DISPLAY" in os.environ: subprocess.call(["xdg-open", viewurl % (volid)])


